version: "3.8"
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: container-backend
    ports:
      - "3000:3000"
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: container-frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
